mysql:
  prefix: core-
  host: mysql.titanaxe.com
  port: 3306
  user: srv207254
  pass: 4d7Q4p88
  name: srv207254
check_allowed_commands:
  - wyslij
  - helpop
config:
  blocked:
    cmd:
      incombat:
        - baza
        - os
        - achievements
        - osiagniecia
        - warp
        - depozyt
        - czas
        - kit
        - spawn
        - home
        - sethome
        - tpa
        - tpaccept
        - tpdeny
        - repair
        - schowek
        - crafting
        - enderchest
        - gildia dom
        - g dom
        - ec
        - schowek
        - depozyt
        - repair all
      inguild:
        - home
        - sethome
        - tpa
        - tpdeny
        - repair
        - crafting
        - wb
        - repair all
enable:
  guilds:
    status: true
    items-normal: 57:0-16:Blok Diametowy;133:0-16:Blok Emeraldu;
    items-vip: 57:0-12:Blok Diametowy;133:0-12:Blok Emeraldu;
    items-svip: 57:0-8:Blok Diametowy;133:0-8:Blok Emeraldu;
  kits:
    status: true
    message: '&cKity dostepne beda o 21:00!'
  pandora:
    status: true
limit:
  kox: 1
  refy: 8
  perly: 3
  sniezki: 8
  arrow: 64
  tnt: 3
automsg:
  - '&7testowa'
  - '&ctestowa2'
wl:
  motd: '&3WaterPE.pl'
  enable: true
  list:
    - VerttyPL
  reason: '&cTrwaja prace techniczne!'
border: 800
borderd: 800.0
protection:
  have-player: '&7Gracz {NAME} posiada ochrone jeszcze przez {TIME}'
  end-title: '&9OCHRONA'
  end-subtitle: '&6Twoja ochrona dobiegla konca'
  actionbar: '&9[OCHRONA] &6{TIME}'
inventory-from-stone: '&c&lDROP ZE STONE'
bc-level: '&7Gracz {NICK} awansowal na {LVL} kopania!'
drop:
  name: '&2{NAME}'
  lore: ' &8>> &6Szansa na drop: &7{CHANCE}%{N} &8>> &6Wypada pomiedzy: &6Y:&70 &6a
    &7{HEIGHT} &6poziomem{N} &8>> &6Szczescie: &a{FORTUNE}{N} &8>> &6Drop: &a{ENABLE}{N}
    &8>> &6Punkty: &7{LVL} &6pkt.{N} &8>> &6Wykopane: &7{WYKOPANE}'
turbo: 0
turbo-exp: 0
exp:
  stone: 3
  obsidian: 5
drops:
  DIAMENT:
    item: 264
    height: 35
    slot: 0
    chance: 2.7
    fortune: true
    lvl: 9
    message: '&7Brawo trafiles na &6{AMOUNT} x Diament'
  SZMARAGD:
    item: 388
    height: 35
    slot: 1
    chance: 2.7
    fortune: true
    lvl: 9
    message: '&7Brawo trafiles na &6{AMOUNT} x Emerald'
  SZTABKA ZLOTA:
    item: 266
    height: 50
    slot: 2
    chance: 2.25
    fortune: true
    lvl: 6
    message: '&7Brawo trafiles na &6{AMOUNT} x Zloto'
  SZTABKA ZELAZA:
    item: 265
    height: 64
    slot: 3
    chance: 3.75
    fortune: false
    lvl: 5
    message: '&7Brawo trafiles na &6{AMOUNT} x Zelazo'
  OBSYDIAN:
    item: 49
    height: 35
    slot: 4
    chance: 2.1
    fortune: true
    lvl: 9
    message: '&7Brawo trafiles na &6{AMOUNT} x Obsydian'
  WEGIEL:
    item: 263
    height: 100
    slot: 5
    chance: 3.0
    fortune: true
    lvl: 1
    message: '&7Brawo trafiles na &6{AMOUNT} x Wegiel'
  REDSTONE:
    item: 331
    height: 35
    slot: 6
    chance: 3.6
    fortune: true
    lvl: 3
    message: '&7Brawo trafiles na &6{AMOUNT} x Redstone'
  KSIAZKA:
    item: 340
    height: 25
    slot: 7
    chance: 2.0
    fortune: false
    lvl: 4
    message: '&7Brawo trafiles na &6{AMOUNT} x Ksiazka'
  PROCH:
    item: 289
    height: 35
    slot: 8
    chance: 2.25
    fortune: true
    lvl: 4
    message: '&7Brawo trafiles na &6{AMOUNT} x Proch'
  PIASEK:
    item: 12
    height: 35
    slot: 9
    chance: 2.5
    fortune: false
    lvl: 1
    message: '&7Brawo trafiles na &6{AMOUNT} x Piasek'
  PERLA:
    item: 368
    height: 35
    slot: 10
    chance: 0.045
    fortune: true
    lvl: 10
    message: '&7Brawo trafiles na &6{AMOUNT} x Perla'
gildia:
  tnt:
    protection_enable: true
    howhour: 24
    explodetime: 120
  prolong:
    start: 7
    max: 1
    add: 7
  life:
    start: 3
    cooldown: 24
  size:
    start: 24
    max: 74
    add: 1
    between: 20
    spawn_distance: 400
slowmode: 5
unknown-command: '&cNie odnaleziono takiej komendy na serwerze &6/pomoc'
format:
  global: '{GUILD}&7{POINTS} &9P{PRESTIZ} {PREFIX}{RANGA} &7{PLAYER} &8>> &r{SUFFIX}{MSG}'
  admin: '{PREFIX}{RANGA} &7{PLAYER} &8>> &r{SUFFIX}{MSG}'
  chat:
    player:
      prefix: '&7'
      suffix: '&7'
      fullname: ''
    vip:
      prefix: '&6'
      suffix: '&7'
      fullname: VIP
    svip:
      prefix: '&e'
      suffix: '&7'
      fullname: SVIP
    yt:
      prefix: '&5'
      suffix: '&7'
      fullname: YOUTUBER
    sponsor:
      prefix: '&3'
      suffix: '&7'
      fullname: SPONSOR
    helper:
      prefix: '&3'
      suffix: '&b'
      fullname: HELPER
    moderator:
      prefix: '&2'
      suffix: '&a'
      fullname: MODERATOR
    admin:
      prefix: '&c'
      suffix: '&e'
      fullname: ADMIN
    headadmin:
      prefix: '&c'
      suffix: '&6'
      fullname: HEADADMIN
    root:
      prefix: '&4'
      suffix: '&6'
      fullname: ROOT
pomoc: TEST{N}TEST
vip: TEST{N}TEST
svip: TEST{N}TEST
sponsor: TEST{N}TEST
yt: TEST{N}TEST
