
package pl.vertty.arivi.objects.yml;

import java.util.Arrays;
import java.util.List;

public class Config
{
    public static String COST_JOIN_NORMAL;
    public static String GUILD_COMMAND_ZGLOS_NAME;
    public static String GUILD_IS_GUILD;
    public static String GUILD_COMMAND_HOME_ERROR;
    public static int CUBOID_SIZE_START;
    public static String GUILD_COMMAND_SOJUSZ_ERROR;
    public static String ANTYLOGAUT_LOGAUT;
    public static String GUILD_PANEL_SOJUSZ_SUBTITLE;
    public static String GUILD_COMMAND_JOIN_ERROR2;
    public static String GUILD_COMMAND_FREESPACE_SUCCESS;
    public static String GUILD_COMMAND_INCOGNITO_SUBTITLE2;
    public static String GUILD_COMMAND_SOJUSZ_MESSAGE;
    public static String GUILD_COMMAND_RESETRANKING_DEATHS_SUCCESS;
    public static String GUILD_TNT_MESSAGE;
    public static int PROLONG_START;
    public static String GUILD_TELEPORT_SUBTITLE3;
    public static String GUILD_COMMAND_KARA_SUCCESS2;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE2;
    public static String COST_CREATE_VIP;
    public static String GUILD_COMMAND_CREATE_TITLE;
    public static String COST_CREATE_NORMAL;
    public static String GUILD_COMMAND_CREATE_MESSAGE;
    public static String GUILD_INTERACT_ERROR2;
    public static String GUILD_COMMAND_CREATE_SUBTITLE;
    public static List<String> CMD_IN_GUILD;
    public static String GUILD_COMMAND_RANKING_ERROR2;
    public static String GUILD_COMMAND_FREESPACE_ERROR;
    public static String GUILD_COMMAND_LEADER_MESSAGE2;
    public static int CUBOID_SIZE_ADD;
    public static String GUILD_PANEL_SKARBIEC_SUBTITLE;
    public static String MOVE_GUILD_JOIN_MESSAGE2;
    public static String GUILD_IS_GUILD2;
    public static String COST_CORDINATE_NORMAL;
    public static String GUILD_PANEL_LIFE_TITLE;
    public static String GUILD_PANEL_PROLONG_SUBTITLE2;
    public static String GUILD_COMMAND_LEAVE_ERROR;
    public static String GUILD_COMMAND_INVITEALL_ERROR;
    public static String GUILD_INTERACT_ERROR;
    public static String GUILD_TNT_ERROR;
    public static String GUILD_PANEL_SKARBIEC_TITLE;
    public static String ANTYLOGAUT_END;
    public static String GUILD_PANEL_LIFE_SUBTITLE2;
    public static String GUILD_COMMAND_USE_GUILD;
    public static String GUILD_COMMAND_INVITEALL_SUCCESS;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE5;
    public static String GUILD_COMMAND_INVITE_MESSAGE;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE;
    public static String GUILD_PANEL_ENLARGE_TITLE;
    public static String COST_CREATE_SVIP;
    public static String GUILD_COMMAND_SOJUSZ_SUCCESS3;
    public static String GUILD_COMMAND_LEAVE_MESSAGE;
    public static String COST_ENLARGE_NORMAL;
    public static String MOVE_GUILD_QUIT_MESSAGE2;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE3;
    public static String GUILD_INTERACT_ERROR1;
    public static List<String> GUILD_COMMAND_HELP_GLOBAL_MESSAGE;
    public static String MOVE_GUILD_QUIT_MESSAGE;
    public static String GUILD_PANEL_EFFECT_SUBTITLE2;
    public static String GUILD_COMMAND_KICK_ERROR1;
    public static String CHAT_ALLY_USAGE;
    public static String GUILD_PANEL_HP_SUBTITLE;
    public static String GUILD_COMMAND_DELETE_MESSAGE;
    public static String GUILD_TELEPORT_SUCCESS;
    public static String COMMAND_USAGE;
    public static String GUILD_COMMAND_LIDER_ERROR;
    public static String GUILD_COMMAND_LIDER_MESSAGE;
    public static String CHAT_GUILD_HELP;
    public static String GUILD_COMMAND_SOJUSZ_ERROR6;
    public static List<String> GUILD_COMMAND_HELP_MESSAGE;
    public static String GUILD_PANEL_SOJUSZ_SUBTITLE2;
    public static int CUBOID_SIZE_BETWEEN;
    public static String GUILD_PANEL_MEMBER_SUBTITLE2;
    public static String GUILD_PANEL_SKARBIEC_SUBTITLE2;
    public static String GUILD_PANEL_SKARBIEC_SUBTITLE3;
    public static String GUILD_PROLONG_TIME;
    public static String GUILD_COMMAND_JOIN_ERROR;
    public static String GUILD_PANEL_PROLONG_TITLE;
    public static String COST_OWNER_NORMAL;
    public static String GUILD_PANEL_MEMBER_TITLE;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE1;
    public static int PROLONG_MAX;
    public static String GUILD_COMMAND_INVITE_SUCCESS2;
    public static String GUILD_COMMAND_CREATE_ERROR4;
    public static String MOVE_INTRUZ_MESSAGE;
    public static int PROLONG_ADD;
    public static String GUILD_COMMAND_DELETE_TITLE;
    public static String GUILD_COMMAND_SOJUSZ_ERROR4;
    public static String GUILD_COMMAND_INVITE_SUCCESS1;
    public static String GUILD_COMMAND_INVITE_ERROR;
    public static String GUILD_PANEL_HP_TITLE;
    public static boolean ENABLE_TNT;
    public static String GUILD_COMMAND_SOJUSZ_ERROR2;
    public static String GUILD_TELEPORT_TITLE;
    public static String GUILD_COMMAND_SOJUSZ_ERROR5;
    public static String GUILD_TELEPORT_SUBTITLE2;
    public static String MOVE_GUILD_JOIN_MESSAGE;
    public static String GUILD_COMMAND_SOJUSZ_SUCCESS;
    public static String GUILD_COMMAND_DELETE_SUBTITLE;
    public static String GUILD_COMMAND_JOIN_MESSAGE;
    public static String GUILD_COMMAND_KICK_MESSAGE;
    public static String GUILD_COMMAND_JOIN_SUCCESS;
    public static String GUILD_COMMAND_JOIN_ERROR1;
    public static String GUILD_INTERACT_MESSAGE;
    public static String GUILD_COMMAND_PVP_SUCCESS1;
    public static String GUILD_PANEL_SOJUSZ_TITLE;
    public static String GUILD_COMMAND_TELEPORT_SUCCESS;
    public static String GUILD_COMMAND_INVITE_MESSAGE2;
    public static String MOVE_INTRUZ_MESSAGE2;
    public static String CHAT_GUILD_USAGE;
    public static String GUILD_COMMAND_CREATE_ERROR2;
    public static String GUILD_COMMAND_SOJUSZ_SUCCESS2;
    public static String GUILD_PANEL_EFFECT_TITLE;
    public static String GUILD_COMMAND_SETHOME_SUCCESS;
    public static String GUILD_COMMAND_CREATE_ERROR1;
    public static String GUILD_COMMAND_LEADER_ERROR2;
    public static String GUILD_NOT_EXISTS;
    public static String GUILD_UPRAWNIENA_ERROR;
    public static String GUILD_COMMAND_RANKING_ERROR;
    public static String GUILD_COMMAND_RESETRANKING_KILLS_SUCCESS;
    public static String GUILD_COMMAND_LEADER_MESSAGE;
    public static String GUILD_NOT_GUILD2;
    public static String GUILD_COMMAND_INFO_ERROR;
    public static String PLAYER_CLICK_SUCCESS;
    public static String GUILD_COMMAND_CREATE_ERROR;
    public static String GUILD_PANEL_ENLARGE_SUBTITLE2;
    public static String GUILD_NOT_GUILD;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE7;
    public static String GUILD_COMMAND_SOJUSZ_ERROR1;
    public static String GUILD_PANEL_SKARBIEC_SUBTITLE5;
    public static String GUILD_COMMAND_SOJUSZ_ERROR3;
    public static String GUILD_COMMAND_RANKING_SUCCESS;
    public static String GUILD_PANEL_MEMBER_SUBTITLE;
    public static String GUILD_NOT_OWNER;
    public static List<String> GUILD_COMMAND_HELP_ADMIN_MESSAGE;
    public static String GUILD_TNT_ERROR2;
    public static String GUILD_COMMAND_KICK_ERROR;
    public static String GUILD_NOT_MYGUILD;
    public static String GUILD_COMMAND_INCOGNITO_SUBTITLE;
    public static String GUILD_COMMAND_LEADER_ERROR;
    public static String GUILD_COMMAND_KARA_SUCCESS;
    public static String GUILD_COMMAND_REGENERATION_TITLE;
    public static String GUILD_PANEL_ENLARGE_SUBTITLE;
    public static String COST_PROLONG_NORMAL;
    public static String GUILD_COMMAND_PVP_SUCCESS2;
    public static String GUILD_COMMAND_SETHOME_ERROR;
    public static List<String> GUILD_COMMAND_INFO_SUCCESS;
    public static String GUILD_COMMAND_ZGLOS_WEBHOOK;
    public static String GUILD_COMMAND_CREATE_ERROR3;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE4;
    public static String GUILD_PANEL_HP_SUBTITLE2;
    public static String GUILD_COMMAND_SOJUSZ_SUCCESS1;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE8;
    public static String GUILD_INTERACT_MESSAGE2;
    public static String GENERATOR_ERROR2;
    public static String GUILD_PANEL_LIFE_SUBTITLE;
    public static String GUILD_COMMAND_SOJUSZ_MESSAGE2;
    public static String COST_LEADER_NORMAL;
    public static String GUILD_COMMAND_CORDINATE_SUCCESS;
    public static String GUILD_COMMAND_REGENERATION_SUBTITLE6;
    public static String GUILD_PANEL_PROLONG_SUBTITLE;
    public static String GUILD_BUILD_CENTER;
    public static String GUILD_PANEL_SKARBIEC_SUBTITLE4;
    public static String GUILD_COMMAND_RESETRANKING_POINTS_SUCCESS;
    public static boolean ENABLE_STONIARKA;
    public static String GUILD_TELEPORT_SUBTITLE;
    public static String USER_NULL;
    public static String GUILD_COMMAND_ZGLOS_SUCCESS;
    public static String GUILD_COMMAND_INCOGNITO_TITLE;
    public static String GUILD_COMMAND_CORDINATE_ERROR;
    public static int CUBOID_SIZE_MAX;
    public static String GUILD_COMMAND_KICK_ERROR2;
    public static String GUILD_UPRAWNIENIA_SUCCESS;
    public static String GENERATOR_ERROR;

    static {
        Config.GUILD_COMMAND_RANKING_SUCCESS = "&7Pomyslnie &9zresetowales &7dane &9gildi";
        Config.GUILD_COMMAND_RANKING_ERROR = "&cMusisz potwierdzic zresetowanie statystyk slowem TAK";
        Config.GUILD_COMMAND_RANKING_ERROR2 = "&cResetowac statystyki gildi mozesz co 30min";
        Config.USER_NULL = "&cNie ma takiego gracza";
        Config.COMMAND_USAGE = "&7Poprawne uzycie: &9{USAGE}";
        Config.GUILD_NOT_EXISTS = "&cNie ma takiej gildi";
        Config.GUILD_NOT_GUILD = "&cNie posiadasz gildi";
        Config.GUILD_COMMAND_JOIN_ERROR2 = "&cTa gildia jest pelna, lider musi dokupic miejsc w panelu gilidyjnym";
        Config.GUILD_IS_GUILD = "&cPosiadasz juz gildie";
        Config.GUILD_NOT_OWNER = "&cNie jestes zalozycielem";
        Config.GUILD_COMMAND_USE_GUILD = "&cNie mozesz uzyc tej komendy na terenie gildi";
        Config.ANTYLOGAUT_END = "&7Skonczyles &9walke&7, mozesz sie &9wylogowac&7!";
        Config.ANTYLOGAUT_LOGAUT = "&cGracz {TAG} &4{NICK} &cwylogowal sie podczas walki";
        Config.GUILD_PANEL_SKARBIEC_TITLE = "&8[&9SKARBIEC&8]";
        Config.GUILD_PANEL_SKARBIEC_SUBTITLE = "&aWplaciles emeraldowy do skarbca";
        Config.GUILD_PANEL_SKARBIEC_SUBTITLE2 = "&cNie masz tyle emeraldow w ekwipunku";
        Config.GUILD_PANEL_SKARBIEC_SUBTITLE3 = "&aWplaciles emeraldy do skarbca";
        Config.GUILD_PANEL_SKARBIEC_SUBTITLE4 = "&cNie masz tyle emeraldow w ekwipunku";
        Config.GUILD_PANEL_SKARBIEC_SUBTITLE5 = "&cZla wartosc!";
        Config.GUILD_NOT_MYGUILD = "&cGracz nie jest w twojej gildi";
        Config.GUILD_IS_GUILD2 = "&cTen gracz posiada juz gildie";
        Config.GUILD_NOT_GUILD2 = "&cTen gracz nie jest w tej gildi";
        Config.GUILD_PROLONG_TIME = "&7Gildia &9{TAG} &7wygasla\n&7Kordy gildi to: x: &9{X} &7z: &9{Z}";
        Config.GUILD_COMMAND_SETHOME_ERROR = "&cDom gildi mozesz ustawic tylko na terenie gildi";
        Config.GUILD_PANEL_EFFECT_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_LIFE_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_COMMAND_ZGLOS_SUCCESS = "&aPomyslnie wyslano zgloszenie";
        Config.GUILD_PANEL_LIFE_SUBTITLE = "&aOdnowiles 1 zycie dla gildi";
        Config.GUILD_COMMAND_ZGLOS_NAME = "Guilds - Notification";
        Config.GUILD_COMMAND_ZGLOS_WEBHOOK = "https://discord.com/api/webhooks/818823997533454366/MzG_AOSUHlIZQgg2v6jqzYZa6Pn546GMnqKjXzObh59auGncKYBxNZmrqYEOWGLL9Pn-";
        Config.GUILD_PANEL_LIFE_SUBTITLE2 = "&cTwoja gildia posiada maksymalna liczbe zyc";
        Config.GUILD_PANEL_HP_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_HP_SUBTITLE = "&aOdnowiles cale hp gildi";
        Config.GUILD_PANEL_HP_SUBTITLE2 = "&cTwoja gildia posiada maksymalna liczbe hp";
        Config.GUILD_PANEL_MEMBER_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_MEMBER_SUBTITLE = "&aPowiekszyles miejsca w gildi o 3";
        Config.GUILD_PANEL_MEMBER_SUBTITLE2 = "&cTwoja gildia posiada maksymalna liczbe czlonkow";
        Config.GUILD_PANEL_SOJUSZ_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_SOJUSZ_SUBTITLE = "&aPowiekszyles limit sojuszy w gildi o 1";
        Config.GUILD_PANEL_SOJUSZ_SUBTITLE2 = "&cTwoja gildia posiada maksymalna liczbe sojuszy";
        Config.GUILD_COMMAND_SETHOME_SUCCESS = "&cUstawiles dom gildi";
        Config.GUILD_COMMAND_RESETRANKING_KILLS_SUCCESS = "&7Pomyslnie ustawiles gildi &9{TAG} &7zabojstwa na &90";
        Config.GUILD_COMMAND_RESETRANKING_DEATHS_SUCCESS = "&7Pomyslnie ustawiles gildi &9{TAG} &7smierci na &90";
        Config.GUILD_COMMAND_RESETRANKING_POINTS_SUCCESS = "&7Pomyslnie ustawiles gildi &9{TAG} &7punkty na &91000";
        Config.GUILD_COMMAND_HOME_ERROR = "&cNie mozesz teleportowac sie na terenie wrogiej gildi";
        Config.GUILD_COMMAND_CREATE_ERROR = "&cIstenieje juz gildia o takim tagu";
        Config.GUILD_COMMAND_CREATE_ERROR1 = "&cIstenieje juz gildia o takiej nazwie";
        Config.GUILD_COMMAND_CREATE_ERROR2 = "&cJestes zbyt blisko spawnu";
        Config.GUILD_COMMAND_CREATE_ERROR3 = "&cW poblizu jest gildia";
        Config.GUILD_COMMAND_CREATE_ERROR4 = "&cTag musi zawierac od 2-4 znakow a nazwa od 4-32 znakow";
        Config.GUILD_COMMAND_CREATE_TITLE = "&4Gratulacje!";
        Config.GUILD_COMMAND_CREATE_SUBTITLE = "&7Zalozyles gildie &9{TAG}";
        Config.GUILD_COMMAND_KARA_SUCCESS = "&cNa gildie &4{TAG} &czostala nalozona kara tnt na &4{TIME} &cprzez &4{ADMIN}";
        Config.GUILD_COMMAND_KARA_SUCCESS2 = "&cKara tnt na terenie gildi &4{TAG} &czostala cofnieta przez &4{ADMIN}";
        Config.GUILD_COMMAND_CREATE_MESSAGE = "&7Gildia &9{TAG} {NAZWA} &7zostala zalozona przez &9{NICK}";
        Config.GUILD_COMMAND_LIDER_MESSAGE = "&7Gracz &9{NICK} &7zostal nowym zalozycielem gildi &9{TAG}";
        Config.GUILD_COMMAND_LIDER_ERROR = "&cNie mozesz sam sobie nadac zalozyciela!";
        Config.GUILD_COMMAND_DELETE_MESSAGE = "&7Gildia &9{TAG} {NAZWA} &7zostala usunieta przez &9{NICK}";
        Config.GUILD_COMMAND_DELETE_TITLE = "&4Gratulacje!";
        Config.GUILD_COMMAND_DELETE_SUBTITLE = "&7Usunales gildie &9{TAG}";
        Config.GUILD_COMMAND_INVITE_ERROR = "&cTen gracz ma juz gildie";
        Config.GUILD_COMMAND_INVITE_SUCCESS1 = "&7Cofnales zaproszenie do gildi graczowi &9{NICK}";
        Config.GUILD_COMMAND_INVITE_SUCCESS2 = "&7Wyslales zaproszenie do gildi graczowi &9{NICK}";
        Config.GUILD_COMMAND_INVITEALL_SUCCESS = "&7Wyslales &9zaproszenia &7do gildi &9graczom &7w poblizu &95 &7kratek &8(&9{PLAYERS}&8)";
        Config.GUILD_COMMAND_INVITEALL_ERROR = "&cW poblizu nie ma zadnego gracza!";
        Config.GUILD_COMMAND_INVITE_MESSAGE = "&7Zaproszenie do gildi &9{TAG} &7zostalo cofniete przez &9{NICK}";
        Config.GUILD_COMMAND_INVITE_MESSAGE2 = "&7Zostales zaproszony do gildi &9{TAG} &7przez &9{NICK}\n&7Wpisz &9/g dolacz {TAG} &7aby dolaczyc";
        Config.GUILD_COMMAND_JOIN_ERROR = "&cTaka gildia nie istnieje";
        Config.GUILD_COMMAND_JOIN_ERROR1 = "&cNie masz zaproszenia do tej gildi";
        Config.GUILD_COMMAND_JOIN_SUCCESS = "&7Dolaczyles do gildi &9{TAG}";
        Config.GUILD_COMMAND_JOIN_MESSAGE = "&7Gracz &9{NICK} &7dolaczyl do gildi &9{TAG}";
        Config.GUILD_COMMAND_KICK_ERROR = "&cTan gracz nie jest w twojej gildi";
        Config.GUILD_COMMAND_KICK_ERROR1 = "&cNie mozesz wyrzucic zalozyciela";
        Config.GUILD_COMMAND_KICK_ERROR2 = "&cNie mozesz wyrzucic samego siebie";
        Config.GUILD_COMMAND_KICK_MESSAGE = "&7Gracz &9{NICK} &7zostal wyrzucony z gildi &9{TAG} &7przez &9{NICK2}";
        Config.GUILD_COMMAND_LEAVE_ERROR = "&cJestes zaloczycielem";
        Config.GUILD_COMMAND_LEAVE_MESSAGE = "&7Gracz &9{NICK} &7opuscil gildie &9{TAG}";
        Config.GUILD_COMMAND_LEADER_ERROR = "&cGracz nie jest w twojej gildi";
        Config.GUILD_COMMAND_LEADER_ERROR2 = "&cNie mozesz usunac zalozyciela";
        Config.GUILD_COMMAND_LEADER_MESSAGE = "&7Gracz &9{NICK} &7nie jest juz zastepca w gildi &9{TAG}";
        Config.GUILD_COMMAND_LEADER_MESSAGE2 = "&7Gracz &9{NICK} &7zostal nowym zastepca w gildi &9{TAG}";
        Config.GUILD_COMMAND_PVP_SUCCESS1 = "&9{NICK} {STATUS} &9pvp &7w &9gildi";
        Config.GUILD_COMMAND_PVP_SUCCESS2 = "&9{NICK} {STATUS} &9pvp &7w &9sojuszu";
        Config.GUILD_COMMAND_SOJUSZ_ERROR = "&cGildia o takim tagu nie istnieje";
        Config.GUILD_COMMAND_SOJUSZ_ERROR1 = "&cNie mozesz zawrzec sojuszu sam ze soba";
        Config.GUILD_COMMAND_SOJUSZ_ERROR2 = "&cNie posiadasz sojuszu z ta gildia";
        Config.GUILD_COMMAND_REGENERATION_TITLE = "&8[&9REGENERACJA&8]";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE = "&cTwoja gildia nie ma nic do zregenerowania";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE1 = "&cRegeneracje mozna uzywac tylko gdy jest wylaczone tnt";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE2 = "&cSkarbiec jest pusty, musisz wplacic przynajmniej 1 emerald";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE3 = "&cZabraklo emeraldow do zregenerowania cuboida ({X})";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE4 = "&aTeren zostal zregenerowany!";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE5 = "&aRozpoczela sie regeneracja terenu";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE6 = "&aRegeneracja terenu zostala wykonana przez {NICK}";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE7 = "&cPodana gildia nie ma nic do zregenerowania";
        Config.GUILD_COMMAND_REGENERATION_SUBTITLE8 = "&cPodana gildia regeneruje juz swoj cuboid";
        Config.GUILD_COMMAND_SOJUSZ_ERROR3 = "&cPosiadasz juz sojusz z ta gildia";
        Config.GUILD_COMMAND_SOJUSZ_ERROR4 = "&cPosiadasz juz 4 sojusze";
        Config.GUILD_COMMAND_SOJUSZ_ERROR5 = "&cTa gildia posiada juz 4 sojusze";
        Config.GUILD_COMMAND_SOJUSZ_ERROR6 = "&cLider tej gildi jest offline";
        Config.GUILD_COMMAND_SOJUSZ_MESSAGE = "&7Gildia &9{TAG} &7zerwala sojusz z gildia &9{TAG2}";
        Config.GUILD_COMMAND_SOJUSZ_MESSAGE2 = "&7Gildia &9{TAG} &7zawarla sojusz z gildia &9{TAG2}";
        Config.GUILD_COMMAND_SOJUSZ_SUCCESS = "&7Zaproszenie do sojuszu z gildia &9{TAG} &7zostalo cofniete";
        Config.GUILD_COMMAND_SOJUSZ_SUCCESS1 = "&7Gildia &9{TAG} &7cofnela zaprosznie do sojuszu";
        Config.GUILD_COMMAND_SOJUSZ_SUCCESS2 = "&7Wyslales zaproszenie do sojusz gildi &9{TAG}";
        Config.GUILD_COMMAND_SOJUSZ_SUCCESS3 = "&7Twoja gildia otrzymala zaproszenie do sojuszu z gildia &9{TAG}\n&7Wpisz &9/g sojusz zawrzyj {TAG}&7, aby zaakceptowac";
        Config.GUILD_COMMAND_INFO_ERROR = "&cGildia o takim tagu nie istnieje";
        Config.GUILD_COMMAND_INFO_SUCCESS = Arrays.asList("&8&m-----------[&r &9{TAG}&8&m-&r &9{NAZWA}&8]&8&m-----------", "&8» &7Zalozyciel: &9{OWNER}", "&8» &7Zastepca: &9{ZASTEPCA}", "&8» &7Punkty: &9{POINTS}", "&8» &7Zabojstwa: &9{KILLS}", "&8» &7Smierci: &9{DEATHS}", "&8» &7Zycia: &9{LIFE}", "&8» &7Utworzona: &9{STARTTIME}", "&8» &7Wygasa za: &9{PROLONG}", "&8» &7Czlonkow: &9{MEMBERS}", "&8&m-----------[&r &9{TAG}&8&m-&r &9{NAZWA}&8]&8&m-----------");
        Config.GUILD_COMMAND_HELP_MESSAGE = Arrays.asList("&8&m----------&8[ &9POMOC GILDIA &8]&m----------", "&8» &9/g zaloz <tag> <nazwa> &8- &7Zaklada gildie", "&8» &9/g usun &8- &7Usuwa gildie", "&8» &9/g znajdz <tag> &8- &7Szuka kordow gildi", "&8» &9/g sojusz <zawrzyj/zerwij> <tag> &8- &7Sojusz gildyjny", "&8» &9/g powieksz &8- &7Powieksza teren gildi", "&8» &9/g zapros &8- &7Zaprasza gracza do gildi", "&8» &9/g zaprosall &8- &7Zaprasza do gildi graczy w poblizu", "&8» &9/g oplac &8- &7Oplaca gildie", "&8» &9/g baza &8- &7Teleportuje do gildi", "&8» &9/g ustawbaze &8- &7Ustawia baze gildi", "&8» &9/g info <tag> &8- &7Informacje o gildi", "&8» &9/g itemy &8- &7Pokazuje itemy na gildie","&8» &9/g dolacz <tag> &8- &7Dolacza do gildi", "&8» &9/g wyrzuc <nick> &8- &7Wyrzuca z gildi", "&8» &9/g zastepca <nick> &8- &7Daje zastepce gildi", "&8» &9/g lider <nick> &8- &7Oddaje wlasciciela gildi", "&8» &9/g opusc &8- &7Opuszcza gildie", "&8» &9/g uprawnienia &8- &7Pokazuje uprawnienia gracza", "&8» &9/g pvp &8- &7Zmienia tryb pvp w gildi", "&8» &9/g pvp sojusz &8- &7Zmienia tryb pvp w sojuszu", "&8» &9/g skarbiec &8- &7Otwiera skarbiec w gildi", "&8» &9/g panel &8- &7Otwiera panel gildyjny", "&8» &9/g kara &8- &7Pokazuje kary gildi", "&8» &9/g wolnemiejsce &8- &7Szuka wolnego miejsca", "&8» &9/g zglos <tag> <powod> &8- &7Zglasza gildie", "&8» &9/g wzywampomoc &8- &7Wzywa pomoc gildyjna", "&8» &9/g top &8- &7Pokazuje topki gildyjne", "&8&m----------&8[ &9POMOC GILDIA &8]&m----------");
        Config.GUILD_COMMAND_HELP_ADMIN_MESSAGE = Arrays.asList("&8&m----------&8[ &9POMOC GILDIA ADMIN &8]&m----------", "&8» &9/ga ban <tag> &8- &7Banuje gildie", "&8» &9/ga tp <tag> <y> &8- &7Teleportuje do gildi", "&8» &9/ga usun <tag> &8- &7Usuwa gildie", "&8» &9/ga ranking <kills/deaths/points> <tag> &8- &7Resetuje statystyki gildi", "&8» &9/ga kara <tag> <czas> &8- &7Nadaje kare tnt gildi", "&8» &9/ga dolacz <tag> <nick> &8- &7Dodaje gracza do gildi", "&8» &9/ga unban <tag> &8- &7Odbanowuje gildie", "&8» &9/ga zalozyciel <tag> <nick> &8- &7Daje zalozyciela gildi", "&8» &9/ga setspawntp &8- &7Ustawia teleport gildyjny", "&8» &9/ga regeneracja <fast/slow> <tag> &8- &7Regeneruje teren gildi", "&8» &9/ga autor &8- &7Wyswietla autora pluginu", "&8&m----------&8[ &9POMOC GILDIA ADMIN &8]&m----------");
        Config.GUILD_COMMAND_HELP_GLOBAL_MESSAGE = Arrays.asList("&8&m----------&8[ &9POMOC GILDIA GLOBAL &8]&m----------", "&8» &9/gg stoniarka <on/off> &8- &7Zarzadzanie stoniarkami na serwerze", "&8» &9/gg farmer <on/off> &8- &7Zarzadzanie farmerami na serwerze", "&8» &9/gg tnt <on/off> &8- &7Zarzadzanie tnt na serwerze", "&8» &9/gg skopiuj &8- &7Skopiuj itemy (farmery/stoniarka)", "&8&m----------&8[ &9POMOC GILDIA GLOBAL &8]&m----------");
        Config.MOVE_INTRUZ_MESSAGE = "&cIntruz &4{NICK} &cwkroczyl na teren twojej gildi";
        Config.MOVE_INTRUZ_MESSAGE2 = "&cIntruz &4{NICK} &copuscil teren twojej gildi";
        Config.MOVE_GUILD_JOIN_MESSAGE = "&8&l### &a&l\u2714 &a{TAG} {NAZWA} &a&l\u2714 &8&l###";
        Config.MOVE_GUILD_JOIN_MESSAGE2 = "&8&l### &c&l\u2714 &c{TAG} {NAZWA} &c&l\u2714 &8&l###";
        Config.MOVE_GUILD_QUIT_MESSAGE = "&8&l### &a&l\u2718 &a{TAG} {NAZWA} &a&l\u2718 &8&l###";
        Config.MOVE_GUILD_QUIT_MESSAGE2 = "&8&l### &c&l\u2718 &c{TAG} {NAZWA} &c&l\u2718 &8&l###";
        Config.GUILD_INTERACT_ERROR = "&cMusisz miec gildie aby podbic";
        Config.GUILD_COMMAND_INCOGNITO_TITLE = "&8[&9INCOGNITO&8]";
        Config.GUILD_COMMAND_INCOGNITO_SUBTITLE = "&aWlaczyles incognito";
        Config.GUILD_COMMAND_INCOGNITO_SUBTITLE2 = "&cWylaczyles incognito";
        Config.GUILD_COMMAND_CORDINATE_ERROR = "&cSzukac gildi mozesz co 30min";
        Config.GENERATOR_ERROR = "&cNie moze byc zadnego bloku nad generatorem!";
        Config.GENERATOR_ERROR2 = "&cNie mozesz podczas walki stawiac stoniarki";
        Config.GUILD_COMMAND_FREESPACE_ERROR = "&cSzukac wonego miejsca gildi mozesz co 30min";
        Config.GUILD_COMMAND_FREESPACE_SUCCESS = "&eX: {X} Z: {Z} &8| &7Odleglosc: &e{KRATKI} kratek";
        Config.GUILD_COMMAND_CORDINATE_SUCCESS = "&eZnalazles kordy gildi {TAG},\n&eX: {X} Z: {Z}";
        Config.GUILD_INTERACT_ERROR1 = "&cNie mozesz podbijac sojusznikow";
        Config.GUILD_INTERACT_ERROR2 = "&cGildie mozna podbic za {TIME}";
        Config.GUILD_INTERACT_MESSAGE = "&7Gildia &9{TAG} &7zostala zniszczona przez gildie &9{TAG2}";
        Config.GUILD_INTERACT_MESSAGE2 = "&7Gildia &9{TAG} &7zostala podbita przez gildie &9{TAG2}";
        Config.GUILD_PANEL_PROLONG_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_PROLONG_SUBTITLE = "&aOplaciles  gildie o {PROLONG} dni";
        Config.GUILD_PANEL_PROLONG_SUBTITLE2 = "&cTwoja gildia jest maksymalnie oplacona";
        Config.GUILD_PANEL_ENLARGE_TITLE = "&8[&9PANEL&8]";
        Config.GUILD_PANEL_ENLARGE_SUBTITLE = "&7Powiekszyles gildie do &9{SIZE}&7x&9{SIZE}";
        Config.GUILD_PANEL_ENLARGE_SUBTITLE2 = "&cTwoja gildia ma najwiekszy rozmiar gildi";
        Config.GUILD_UPRAWNIENA_ERROR = "&cNie masz uprawnien aby to zrobic, popros lidera o nadanie";
        Config.PLAYER_CLICK_SUCCESS = "&7Ranking gracza &9{NICK} &7wynosi &9{POINTS}\n&8>>    &7Otrzymasz &a{PLUS} &7punktow\n&8>>    &7Straci &c{MINUS} &7punktow";
        Config.GUILD_TELEPORT_SUCCESS = "&aPrzeteleportowano pomyslnie";
        Config.GUILD_BUILD_CENTER = "&cNie mozesz budowac w centrum gildi";
        Config.GUILD_TELEPORT_TITLE = "&8[&9Teleport&8]";
        Config.GUILD_TELEPORT_SUBTITLE = "&aPrzeteleportowano";
        Config.GUILD_TELEPORT_SUBTITLE2 = "&aTrwa teleportacja {TIME} sek";
        Config.GUILD_TELEPORT_SUBTITLE3 = "&cAnulowano teleport";
        Config.CHAT_GUILD_USAGE = "&a[GILDIA] {NICK} -> {MESSAGE}";
        Config.CHAT_ALLY_USAGE = "&6[SOJUSZ] {TAG} {NICK} -> {MESSAGE}";
        Config.CHAT_GUILD_HELP = "&a[GILDIA] {NICK}: Potrzebuje pomocy\n&aMoje kordy to X: {X} Z: {Z}";
        Config.GUILD_TNT_ERROR = "&cTnt dziala pomiedzy 16-22";
        Config.GUILD_TNT_ERROR2 = "&cTnt jest aktualnie wylaczone";
        Config.GUILD_TNT_MESSAGE = "&cNa terenie gildi wybuchlo tnt, Budowac mozesz dopiero za {X}";
        Config.GUILD_COMMAND_TELEPORT_SUCCESS = "&7Ustawiles &9teleport &7gildyjny na kordynatach X: &9{X} &7Y: &9{Y} &7Z: &9{Z}";
        Config.GUILD_UPRAWNIENIA_SUCCESS = "&7Nadales role &9{ROLE} &7graczowi &9{NICK}";
        Config.COST_CREATE_NORMAL = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;";
        Config.COST_CREATE_VIP = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;";
        Config.COST_CREATE_SVIP = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;";

//        Config.COST_CREATE_NORMAL = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;266:0-64:Sztabki zlota;388:0-64:Emeraldy;263:0-64:Wegiel;466:0-1:Kox;322:0-8:Refile;368:0-3:Perly;47:0-32:Biblioteczki;3:0-64:Dirt;49:0-64:Obsydian;145:0-8:Kowadla;";
//        Config.COST_CREATE_VIP = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;266:0-64:Sztabki zlota;388:0-64:Emeraldy;263:0-64:Wegiel;466:0-1:Kox;322:0-8:Refile;368:0-3:Perly;47:0-32:Biblioteczki;3:0-64:Dirt;49:0-64:Obsydian;145:0-8:Kowadla;";
//        Config.COST_CREATE_SVIP = "264:0-64:Diamenty;265:0-64:Sztabki zelaza;266:0-64:Sztabki zlota;388:0-64:Emeraldy;263:0-64:Wegiel;466:0-1:Kox;322:0-8:Refile;368:0-3:Perly;47:0-32:Biblioteczki;3:0-64:Dirt;49:0-64:Obsydian;145:0-8:Kowadla;";



        Config.COST_JOIN_NORMAL = "264:0-10:Diament;";
        Config.COST_LEADER_NORMAL = "264:0-10:Diament;";
        Config.COST_OWNER_NORMAL = "264:0-10:Diament;";
        Config.COST_CORDINATE_NORMAL = "264:0-10:Diament;";
        Config.COST_ENLARGE_NORMAL = "264:0-10:Diament;";
        Config.COST_PROLONG_NORMAL = "264:0-10:Diament;";
        Config.CUBOID_SIZE_START = 24;
        Config.CUBOID_SIZE_MAX = 50;
        Config.CUBOID_SIZE_ADD = 1;
        Config.CUBOID_SIZE_BETWEEN = 20;
        Config.PROLONG_START = 7;
        Config.PROLONG_MAX = 1;
        Config.PROLONG_ADD = 2;
        Config.CMD_IN_GUILD = Arrays.asList("home", "sethome", "tpa", "tpaccept", "tpdeny", "repair", "crafting", "enderchest", "gildia dom", "g dom", "repair all");
        Config.ENABLE_TNT = true;
        Config.ENABLE_STONIARKA = true;
    }
}
